language: r
cache: packages
sudo: false
warnings_are_errors: true

os:
  - linux
  - osx

latex: false

r:
  - 3.2
  - oldrel
  - release
  - devel

matrix:
  allow_failures:
    - r: devel
    - r: 3.2

script:
- R CMD build .
- R CMD check --as-cran --no-manual *tar.gz
