# sudo: required
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - libarpack2-dev
            - libarpack++2-dev
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - libarpack2-dev
            - libarpack++2-dev
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7
