# sudo: required
language: r
cache: packages

os:
  - linux
  - osx

latex: false

r:
  #- oldrel
  - release
  #- devel

compiler:
  - g++
  #- clang

addons:
  apt:
    packages:
      - libarpack2-dev
      - libarpack++2-dev

#before_install:
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update     ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc; fi

