# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kernmat_Matern32_cpp <- function(X1, X2, Z1, Z2, parameters) {
    .Call(`_ace_kernmat_Matern32_cpp`, X1, X2, Z1, Z2, parameters)
}

kernmat_Matern32_symmetric_cpp <- function(X, Z, parameters) {
    .Call(`_ace_kernmat_Matern32_symmetric_cpp`, X, Z, parameters)
}

grad_Matern_cpp <- function(y, X, Z, Kfull, K, invKmatn, eigenval, parameters, stats, B, std_y) {
    .Call(`_ace_grad_Matern_cpp`, y, X, Z, Kfull, K, invKmatn, eigenval, parameters, stats, B, std_y)
}

kernmat_SE_cpp <- function(X1, X2, Z1, Z2, parameters) {
    .Call(`_ace_kernmat_SE_cpp`, X1, X2, Z1, Z2, parameters)
}

kernmat_SE_symmetric_cpp <- function(X, Z, parameters) {
    .Call(`_ace_kernmat_SE_symmetric_cpp`, X, Z, parameters)
}

invkernel_cpp <- function(pdmat, sigma) {
    .Call(`_ace_invkernel_cpp`, pdmat, sigma)
}

grad_SE_cpp <- function(y, X, Z, Kfull, K, invKmatn, eigenval, parameters, stats, B, std_y) {
    .Call(`_ace_grad_SE_cpp`, y, X, Z, Kfull, K, invKmatn, eigenval, parameters, stats, B, std_y)
}

ncs_basis <- function(x, knots) {
    .Call(`_ace_ncs_basis`, x, knots)
}

ncs_basis_deriv <- function(x, knots) {
    .Call(`_ace_ncs_basis_deriv`, x, knots)
}

Nesterov_cpp <- function(learn_rate, momentum, nu, grad, para) {
    .Call(`_ace_Nesterov_cpp`, learn_rate, momentum, nu, grad, para)
}

Nadam_cpp <- function(iter, learn_rate, beta1, beta2, eps, m, v, grad, para) {
    .Call(`_ace_Nadam_cpp`, iter, learn_rate, beta1, beta2, eps, m, v, grad, para)
}

Adam_cpp <- function(iter, learn_rate, beta1, beta2, eps, m, v, grad, para) {
    .Call(`_ace_Adam_cpp`, iter, learn_rate, beta1, beta2, eps, m, v, grad, para)
}

pred_cpp <- function(y_X, sigma, mu, invK_XX, K_xX, K_xx, mean_y, std_y) {
    .Call(`_ace_pred_cpp`, y_X, sigma, mu, invK_XX, K_xX, K_xx, mean_y, std_y)
}

pred_marginal_cpp <- function(y_X, Z_x, sigma, mu, invK_XX, K_xX, K_xx, mean_y, std_y, std_Z, calculate_ate) {
    .Call(`_ace_pred_marginal_cpp`, y_X, Z_x, sigma, mu, invK_XX, K_xX, K_xx, mean_y, std_y, std_Z, calculate_ate)
}

stats_cpp <- function(y, Kmat, invKmatn, eigenval, mu, std_y = 1) {
    .Call(`_ace_stats_cpp`, y, Kmat, invKmatn, eigenval, mu, std_y)
}

mu_solution_cpp <- function(y, invKmat) {
    .Call(`_ace_mu_solution_cpp`, y, invKmat)
}

normalize_train <- function(y, X, Z) {
    .Call(`_ace_normalize_train`, y, X, Z)
}

normalize_test <- function(X, Z, moments) {
    invisible(.Call(`_ace_normalize_test`, X, Z, moments))
}

norm_clip_cpp <- function(flag, grads, max_length) {
    invisible(.Call(`_ace_norm_clip_cpp`, flag, grads, max_length))
}

